### ISSUE TITLE
python的版本

### ISSUE THREAD

**Issue by Vector3q** [woshidandan/TANet#13]
Hi, 我在配置实验环境的时候使用了python3.5 3.6 3.7 三个版本都无法成功配置，想问问大佬原始版本是哪个

**Comment by Vector3q** [comment]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\new\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda3\envs\new\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\new\Scripts\nnictl.exe\__main__.py", line 7, in <module>
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\tools\nnictl\nnictl.py", line 503, in parse_args
    args.func(args)
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\tools\nnictl\launcher.py", line 91, in create_experiment
    exp.start(port, debug, RunMode.Detach)
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\experiment\experiment.py", line 135, in start
    self._start_impl(port, debug, run_mode, None, [])
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\experiment\experiment.py", line 94, in _start_impl
    config = self.config.canonical_copy()
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\experiment\config\base.py", line 166, in canonical_copy
    canon._canonicalize([])
  File "E:\Anaconda3\envs\new\lib\site-packages\nni\experiment\config\experiment_config.py", line 123, in _canonicalize
    if algo is not None and algo.name == '_none_':  # type: ignore
AttributeError: 'dict' object has no attribute 'name'

出现以上报错
